# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - production
    docker:
      # specify the version you desire here
      - image: circleci/node:10.18.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Creating .npmrc
          command: |
            echo "@fortawesome:registry=https://npm.fontawesome.com/" >> ~/.npmrc
            echo "//npm.fontawesome.com/:_authToken=$FONTAWESOME_TOKEN" >> ~/.npmrc

      - run:
          name: Install npm packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build React app
          command: npm run build:$CIRCLE_BRANCH

      - run:
          name: Building artifacts
          command: |
            mkdir /tmp/artifacts;
            mkdir /tmp/artifacts/client;
            cp -r /home/circleci/repo/client/dist /tmp/artifacts/client;
            cp -r /home/circleci/repo/server /tmp/artifacts;
            cp /home/circleci/repo/package.json /tmp/artifacts/package.json;
            cp /home/circleci/repo/package-lock.json /tmp/artifacts/package-lock.json;
            cp ~/.npmrc /tmp/artifacts/.npmrc;
            tar czf build.tar --directory=/tmp/artifacts ./;

      - store_artifacts:
          path: build.tar
          destination: build
